security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        utilisateur_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email # Use the username field for authentication

    # Configuration correcte du firewall
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: utilisateur_provider
            entry_point: form_login  # Ajoutez cette ligne

            # Enable form login
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: app_home
                # Utilisez le success handler personnalisé au lieu de default_target_path
                success_handler: App\Security\LoginSuccessHandler
                # Désactivez ces options pour permettre au handler de fonctionner
                # always_use_default_target_path: false
                use_referer: false
                use_forward: false
                
            custom_authenticators:
                - App\Security\GoogleAuthenticator  # Assurez-vous que ceci correspond au namespace

            logout:
                path: app_logout
                target: app_login

            # Ajouter cette section pour autoriser les routes de réinitialisation de mot de passe
            # access_control:
            #     - { path: ^/reset-password, roles: PUBLIC_ACCESS }

    # L'option access_control doit être ICI, au même niveau que firewalls
    access_control:
        # Routes publiques en premier
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/signup$, roles: PUBLIC_ACCESS }
        - { path: ^/login_check$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        
        # Routes OAuth Google (ajoutez ces lignes)
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        
        # Routes qui nécessitent authentification
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/reclamer, roles: ROLE_USER }
        
        # Routes temporairement ouvertes pour débogage
        - { path: ^/DashboardClient, roles: PUBLIC_ACCESS }
        - { path: ^/admin/user, roles: PUBLIC_ACCESS }


        # Routes Gestion voyages
        - { path: ^/AjouterOffre, roles: PUBLIC_ACCESS }
        - { path: ^/AjouterVoyage, roles: PUBLIC_ACCESS }
        - { path: ^/Bienvenue, roles: PUBLIC_ACCESS }
        - { path: ^/statsAgence, roles: PUBLIC_ACCESS }
        - { path: "^/offres/Details/[0-9]+$", roles: PUBLIC_ACCESS }
        - { path: ^/agence/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/ModifierVoyage/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/Supprimer/Voyage/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/modifierOffre/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/modifierOffreBd/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/supprimerOffre/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/ModifierVoyagebd/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/offresAgence, roles: PUBLIC_ACCESS }
        - { path: ^/offreAgence/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/offres, roles: PUBLIC_ACCESS }
        - { path: ^/offres/suggestions, roles: PUBLIC_ACCESS }
        - { path: ^/offres/Details/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/AjoutOffre, roles: PUBLIC_ACCESS }
        - { path: ^/confirmationAjoutOffre, roles: PUBLIC_ACCESS }
        - { path: ^/publierOffre, roles: PUBLIC_ACCESS }
        - { path: ^/agence/statistiques, roles: PUBLIC_ACCESS }
        - { path: ^/agence/statistiques/voyages/csv, roles: PUBLIC_ACCESS }
        - { path: ^/agence/statistiques/offres/pdf, roles: PUBLIC_ACCESS }
        - { path: ^/agence/statistiques/voyages/excel, roles: PUBLIC_ACCESS }
        - { path: ^/agence/voyage/[0-9]+$/export-ics, roles: PUBLIC_ACCESS }
        - { path: ^/VoyagesAdmin, roles: PUBLIC_ACCESS }
        - { path: ^/VoyagesAgence, roles: PUBLIC_ACCESS }
        - { path: ^/voyageAgence/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/VoyagesClient, roles: PUBLIC_ACCESS }
        - { path: "^/voyage/[0-9]+$", roles: PUBLIC_ACCESS }
        - { path: ^/Reservervoyage/[0-9]+$, roles: PUBLIC_ACCESS }
        - { path: ^/voyages/suggestions, roles: PUBLIC_ACCESS }
        - { path: ^/AjoutVoyage, roles: PUBLIC_ACCESS }
        - { path: ^/confirmationAjout, roles: PUBLIC_ACCESS }
        - { path: ^/publierVoyage, roles: PUBLIC_ACCESS }


        # Routes Gestion réservations
        - { path: ^/PanierClient, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/delete/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/[ 0-9 ]+/update, roles: PUBLIC_ACCESS }
        - { path: ^/panier/confirm/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/HistoriqueClient, roles: PUBLIC_ACCESS }
        - { path: ^/ReservationAdmin, roles: PUBLIC_ACCESS }
        - { path: ^//panier/confirm/success/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/panier/confirm/success, roles: ROLE_USER }


        # Routes Gestion interactions
        - { path: ^/new, roles: PUBLIC_ACCESS }
        - { path: ^/ChatClient, roles: PUBLIC_ACCESS }
        - { path: ^/post/[ 0-9 ]+/like, roles: PUBLIC_ACCESS }
        - { path: ^/[ 0-9 ]+/edit, roles: PUBLIC_ACCESS }
        - { path: ^/post/[ 0-9 ]+/delete, roles: PUBLIC_ACCESS }
        - { path: ^/post/[ 0-9 ]+/details, roles: PUBLIC_ACCESS }
        - { path: ^/commentaire/new/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/post/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/comment/[ 0-9 ]+/edit, roles: PUBLIC_ACCESS }
        - { path: ^/commentaire/[ 0-9 ]+/delete, roles: PUBLIC_ACCESS }
        - { path: ^/PublicationsAdmin, roles: PUBLIC_ACCESS }
        - { path: ^/PublicationsAdmin/export-csv, roles: PUBLIC_ACCESS }
        - { path: ^/PublicationsAdmin/post/[ 0-9 ]+/traiter, roles: PUBLIC_ACCESS }
        - { path: ^/PublicationsAdmin/post/[ 0-9 ]+/delete, roles: PUBLIC_ACCESS }
        



        # Routes Gestion Transport
        - { path: ^/TrajetsAdmin/liste, roles: PUBLIC_ACCESS }
        - { path: ^/TrajetsAdmin/ajouter, roles: PUBLIC_ACCESS }
        - { path: ^/TrajetsAdmin/modifier/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/TrajetsAdmin/supprimer/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/trajets, roles: PUBLIC_ACCESS }
        - { path: ^/trajets/liste, roles: PUBLIC_ACCESS }
        - { path: ^/trajets/ajouter, roles: PUBLIC_ACCESS }
        - { path: ^/trajets/modifier/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/trajets/supprimer/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/TransportsAdmin, roles: PUBLIC_ACCESS }
        - { path: ^/TransportsAdmin/liste, roles: PUBLIC_ACCESS }
        - { path: ^/TransportsAdmin/ajouter, roles: PUBLIC_ACCESS }
        - { path: ^/TransportsAdmin/modifier/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/TransportsAdmin/supprimer/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/transports, roles: PUBLIC_ACCESS }
        - { path: ^/transports/liste, roles: PUBLIC_ACCESS }
        - { path: ^/transports/ajouter, roles: PUBLIC_ACCESS }
        - { path: ^/transports/modifier/[ 0-9 ]+, roles: PUBLIC_ACCESS }
        - { path: ^/transports/supprimer/[ 0-9 ]+, roles: PUBLIC_ACCESS }

        # Règle générale - utilisez IS_AUTHENTICATED_ANONYMOUSLY au lieu de PUBLIC_ACCESS
        # pour les routes qui devraient être accessibles sans authentification
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
